---

- hosts: all
  become: true
  tasks:

  - name: Install Apache Package & Apache PHP Support
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes