- name: Install apache Package & apache PHP Support for Ubuntu & CentOS
  tags: apache,httpd,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start httpd on CentOS
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Change E-Mail Address for apache Admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin zshift47@gmail.net
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: Copy Default HTML File for Site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: Copy Default CSS File for Site
  tags: apache,apache2,httpd
  copy:
    src: default_styles.css
    dest: /var/www/html/styles.css
    owner: root
    group: root
    mode: 0644